import type { CardDefinition } from './cardTypes.js';

const sampleCards: CardDefinition[] = [
  {
    id: 'card-001',
    title: 'Launch Pad',
    heightPct: 100,
    widthPct: 100,
    difficulty: 10,
    gates: {
      top: { width: 90 },
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 12, count: 2 }],
    theme: { bgColor: '#0f172a' },
  },
  {
    id: 'card-002',
    title: 'Switchback Span',
    heightPct: 110,
    widthPct: 100,
    difficulty: 18,
    gates: {
      top: [
        { width: 45, gate: { position: 40 } },
        { width: 55, y: 100 },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 22, count: 3 }],
    theme: { bgColor: '#111827' },
  },
  {
    id: 'card-003',
    title: 'Catwalk Trio',
    heightPct: 95,
    widthPct: 100,
    difficulty: 22,
    gates: {
      top: [
        { width: 30 },
        { width: 40, y: -80, gate: true },
        { width: 30, y: 140 },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 28, count: 4 }],
    theme: { bgColor: '#1e1b4b' },
  },
  {
    id: 'card-004',
    title: 'Orbit Hinge',
    heightPct: 105,
    widthPct: 100,
    difficulty: 26,
    gates: {
      top: [
        { width: 50 },
        { type: 'vertical', height: 260, gate: { position: 65 } },
        { width: 50 },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 32, count: 3 }],
    theme: { bgColor: '#312e81' },
  },
  {
    id: 'card-005',
    title: 'Helix Ladder',
    heightPct: 120,
    widthPct: 100,
    difficulty: 32,
    gates: {
      top: [
        { width: 35, gate: { position: 30, width: 45 } },
        { width: 65, y: -120 },
        { width: 35, y: 180 },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 36, count: 5 }],
    theme: { bgColor: '#1a2a4a' },
  },
  {
    id: 'card-006',
    title: 'Echo Arch',
    heightPct: 90,
    widthPct: 100,
    difficulty: 20,
    gates: {
      top: [
        { width: 60 },
        { type: 'vertical', height: 180 },
        { width: 40, gate: true },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 24, count: 2 }],
    theme: { bgColor: '#0b2545' },
  },
  {
    id: 'card-007',
    title: 'Stagger Step',
    heightPct: 100,
    widthPct: 100,
    difficulty: 24,
    gates: {
      top: [
        { width: 40 },
        { width: 50, y: 120, gate: { position: 60 } },
        { width: 30, y: -100 },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 30, count: 3 }],
    theme: { bgColor: '#102a43' },
  },
  {
    id: 'card-008',
    title: 'Siderail Bridge',
    heightPct: 115,
    widthPct: 100,
    difficulty: 30,
    gates: {
      top: {
        segments: [
          { type: 'horizontal', width: 30 },
          { type: 'vertical', height: 220, gate: { position: 40 } },
          { type: 'horizontal', width: 70, gate: true },
        ],
      },
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 34, count: 4 }],
    theme: { bgColor: '#182747' },
  },
  {
    id: 'card-009',
    title: 'Cascade Rail',
    heightPct: 98,
    widthPct: 100,
    difficulty: 28,
    gates: {
      top: [
        { width: 30, gate: { position: 70 } },
        { width: 50, y: -140 },
        { width: 20, y: 160 },
        { width: 40, y: -80 },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 40, count: 5 }],
    theme: { bgColor: '#1d1f33' },
  },
  {
    id: 'card-010',
    title: 'Zenith Span',
    heightPct: 130,
    widthPct: 100,
    difficulty: 38,
    gates: {
      top: [
        { width: 25 },
        { type: 'vertical', height: 200, gate: { position: 30, width: 35 } },
        { width: 50, y: 120, gate: true },
        { width: 25, y: -140 },
      ],
      right: null,
      bottom: null,
      left: null,
    },
    enemies: [{ difficulty: 45, count: 4 }],
    theme: { bgColor: '#111d4a' },
  },
];

export default sampleCards;
